name: Tests

on:
  push:
    branches:
    - main
    - dev
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-20.04

    steps:
    - name: Say hello world
      run: echo "Welcome to the Github Actions workshop !"

  # Permet de faire un nouveau job et de voir les étapes sur github
  unit-test:
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker

    steps:
    - uses: actions/checkout@v2
    - name: unit-test
    #Créer un artefact
      run: make tests_run > coverage_outputs
      # un tiret par nouvel étape.
    - run: make coverage > coverage_outputs
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: coverage_outputs
      # run: make tests_run
    # - run: make coverage